### ISSUE TITLE
P1 | Especificação de requisitos - Informações incompletas na seção '4.5 Requisitos Detalhados de Casos de Uso'

### ISSUE THREAD

**Issue by yuripopic** [yuripopic/Sistema-de-Judocas#11]
**Linha/Seção:** Seção 4.5 Requisitos Detalhados de Casos de Uso

**Categoria:** Inconsistência

**Descrição:** A seção '4.5 Requisitos Detalhados de Casos de Uso' está incompleta, pois o arquivo AOO_FPIJ_Especificacao_de_Requisitos_SRS possui 3 requisitos detalhados de casos de uso e o arquivo JitaKyoei-SRS possui 28 requisitos detalhados de casos de uso

**Criticidade:** Alta

**Comment by forgelucas** [comment]
Corrigido no commit [160f13a](https://github.com/yuripopic/Sistema-de-Judocas/wiki/Especifica%C3%A7%C3%A3o-de-Requisitos/160f13a9478685048f6b622bba51ce74a5e46767)
