### ISSUE TITLE
P2 | Especificação de requisitos - Informações incompletas na seção '5 Requisitos Não-Funcionais'

### ISSUE THREAD

**Issue by forgelucas** [yuripopic/Sistema-de-Judocas#12]
Linha/Seção: Seção 5 Requisitos Não-Funcionais

Categoria: Inconsistência

Descrição: A seção '5 Requisitos Não-Funcionais' está incompleta, pois arquivo AOO_FPIJ_Especificacao_de_Requisitos_SRS possui 1 requisito não-funcional e o arquivo JitaKyoei-SRS possui 3 requisitos não-funcionais

Criticidade: Alta

**Comment by yuripopic** [comment]
Corrigido no commit [74ed4b3](https://github.com/yuripopic/Sistema-de-Judocas/wiki/Especifica%C3%A7%C3%A3o-de-Requisitos/74ed4b35704295c1611722c9479d0cbcd890f955)
