### ISSUE TITLE
P3 | Especificação de requisitos - Siglas 'E' e 'H' sem significado na seção '4.3 Casos de Uso'

### ISSUE THREAD

**Issue by filipe-pedroso** [yuripopic/Sistema-de-Judocas#13]
Linha/Seção: Seção '4.3 Casos de Uso'

Categoria: Omissão

Descrição: As siglas 'E' e 'H' não foram definidas na seção '4.3 Casos de Uso' 

Criticidade: Baixa

**Comment by yuripopic** [comment]
Corrigido no commit [6296010](https://github.com/yuripopic/Sistema-de-Judocas/wiki/Especifica%C3%A7%C3%A3o-de-Requisitos/6296010bb58042a15eec59cc67905541415d045c)
