### ISSUE TITLE
P4 | Diagrama de Caso de Uso - Está faltando 5 casos de uso no diagrama

### ISSUE THREAD

**Issue by yuripopic** [yuripopic/Sistema-de-Judocas#14]
Linha/Seção: [Casos de Uso](https://github.com/yuripopic/Sistema-de-Judocas/wiki/Casos-de-uso)

Categoria: Omissão

Descrição: Está faltando os seguintes casos de uso no diagrama: 
E3-Apagar Aluno, E7-Apagar Professor,  E11-Apagar Entidade, E13-Emitir Relatórios e E15-Relatório de Aniversariantes 

Criticidade: Alta

**Comment by filipe-pedroso** [comment]
corrigido no commit 2341700cefdea884accad8bb713af542deb4ed96
