### ISSUE TITLE
P5 | Diagrama de Caso de Uso - Não existe o caso de uso 'renovar carteira de filiado' na especificação de requisitos

### ISSUE THREAD

**Issue by forgelucas** [yuripopic/Sistema-de-Judocas#15]
Linha/Seção: [Casos de Uso](https://github.com/yuripopic/Sistema-de-Judocas/wiki/Casos-de-uso)

Categoria: Inconsistência

Descrição: Existe um caso de uso chamado 'renovar carteira de filiado' no diagrama, mas ele não existe nos requisitos  

Criticidade: Alta

**Comment by filipe-pedroso** [comment]
corrigido no commit 2341700cefdea884accad8bb713af542deb4ed96
